[build]
  command = "npm run build"
  publish = "out"

[dev]
  command = "npm run dev"
  port = 8888

[functions]
  directory = "netlify/functions"

[context.production.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
